---
- name: Install JDK
  hosts: solr
  remote_user: ubuntu
  become: true

  tasks:

  - name: Update the apt package index
    apt:
      update_cache: yes

  - name: Upgrade all packages to the latest version
    apt:
      upgrade: dist

  - name: Ensure JDK is at the latest version
    ansible.builtin.apt:
      name: default-jdk-headless
      state: latest

- name: Install Solr
  hosts: solr
  remote_user: ubuntu
  become: true

  tasks:
  - name: Download Solr Package
    ansible.builtin.get_url:
      url: https://archive.apache.org/dist/solr/solr/9.6.0/solr-9.6.0.tgz
      dest: /opt/solr-9.6.0.tgz
      mode: '0440'

  - name: Download Solr Installer
    ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/apache/solr/main/solr/bin/install_solr_service.sh
      dest: /opt/install_solr_service.sh
      mode: '0750'

  - name: Run install command
    ansible.builtin.command: "bash ./install_solr_service.sh solr-9.6.0.tgz -n -f"
    args:
      chdir: /opt

  - name: Set correct permissions
    ansible.builtin.command: "chown -R solr:solr /opt/solr-9.6.0"
    args:
      chdir: /opt

  - name: Set correct permissions
    ansible.builtin.command: "chown -h solr:solr /opt/solr"
    args:
      chdir: /opt

  - name: Copy the solr.service file from local to remote
    ansible.builtin.copy:
      src: etc/systemd/system/solr.service
      dest: /etc/systemd/system/solr.service

  - name: Start Solr service
    ansible.builtin.systemd:
      name: solr
      state: started

  - name: Enable Solr service
    ansible.builtin.systemd:
      name: solr
      enabled: yes