---
- name: Install JDK
  hosts: workbench
  remote_user: ubuntu
  become: true

  tasks:

  - name: Update APT Repositories
    ansible.builtin.apt:
      update_cache: true


  - name: Ensure JDK is at the latest version
    ansible.builtin.apt:
      name: default-jdk-headless
      state: latest

- name: Install Solr
  hosts: workbench
  remote_user: ubuntu
  become: true

  tasks:
  - name: Download Solr Package
    ansible.builtin.get_url:
      url: https://www.apache.org/dyn/closer.lua/solr/solr/9.1.1/solr-9.1.1.tgz?action=download
      dest: /opt/solr-9.1.1.tgz
      mode: '0440'

  - name: Download Solr Installer
    ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/apache/solr/main/solr/bin/install_solr_service.sh
      dest: /opt/install_solr_service.sh
      mode: '0440'
     
  # free-form (string) arguments, all arguments on one line
  - name: Run command if /path/to/database does not exist (without 'args')
    ansible.builtin.command: sudo bash ./install_solr_service.sh solr-9.1.1.tgz 
    args:
      chdir: /opt
