aws_region         = "us-east-1"
ami_id             = "ami-058b428b3b45defec"
instance_type      = "t4g.small"
security_group_id  = "sg-08c6ad6d"
subnet_id          = "subnet-a7407e8f"
key_name           = "Streamlit"
instance_name      = "MySolrServerInstance"
